name: follicles-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scikit-learn
  - pandas
  - matplotlib
  - jupyter
  - pytorch
  - torchvision
  - opencv

  # dev
  - black
  - flake8

  - pip
  - pip:
    - imageio
    - scipy
    - tensorflow==2.6.2
    - osfclient
    - ramp-workflow
