name: follicles-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scikit-learn
  - pandas
  - matplotlib
  - jupyter

  # dev
  - black
  - flake8

  - pip
  - pip:
    - torch 
    - torchvision
    - imageio
    - scipy
    - tensorflow==2.6.2
    - osfclient
    - ramp-workflow
    - opencv-python
